# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.10.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.10.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Ryan/Desktop/Code/DistributedSystem

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Ryan/Desktop/Code/DistributedSystem

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.10.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.10.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Ryan/Desktop/Code/DistributedSystem/CMakeFiles /Users/Ryan/Desktop/Code/DistributedSystem/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Ryan/Desktop/Code/DistributedSystem/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named psu_thread_test

# Build rule for target.
psu_thread_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 psu_thread_test
.PHONY : psu_thread_test

# fast build rule for target.
psu_thread_test/fast:
	$(MAKE) -f CMakeFiles/psu_thread_test.dir/build.make CMakeFiles/psu_thread_test.dir/build
.PHONY : psu_thread_test/fast

#=============================================================================
# Target rules for targets named psu_dsm_server

# Build rule for target.
psu_dsm_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 psu_dsm_server
.PHONY : psu_dsm_server

# fast build rule for target.
psu_dsm_server/fast:
	$(MAKE) -f CMakeFiles/psu_dsm_server.dir/build.make CMakeFiles/psu_dsm_server.dir/build
.PHONY : psu_dsm_server/fast

#=============================================================================
# Target rules for targets named psu_dist_lock_mgr_test

# Build rule for target.
psu_dist_lock_mgr_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 psu_dist_lock_mgr_test
.PHONY : psu_dist_lock_mgr_test

# fast build rule for target.
psu_dist_lock_mgr_test/fast:
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_test.dir/build.make CMakeFiles/psu_dist_lock_mgr_test.dir/build
.PHONY : psu_dist_lock_mgr_test/fast

#=============================================================================
# Target rules for targets named psu_dsm_test

# Build rule for target.
psu_dsm_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 psu_dsm_test
.PHONY : psu_dsm_test

# fast build rule for target.
psu_dsm_test/fast:
	$(MAKE) -f CMakeFiles/psu_dsm_test.dir/build.make CMakeFiles/psu_dsm_test.dir/build
.PHONY : psu_dsm_test/fast

#=============================================================================
# Target rules for targets named psu_dist_lock_mgr_server

# Build rule for target.
psu_dist_lock_mgr_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 psu_dist_lock_mgr_server
.PHONY : psu_dist_lock_mgr_server

# fast build rule for target.
psu_dist_lock_mgr_server/fast:
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_server.dir/build.make CMakeFiles/psu_dist_lock_mgr_server.dir/build
.PHONY : psu_dist_lock_mgr_server/fast

psu_dist_lock_mgr.o: psu_dist_lock_mgr.c.o

.PHONY : psu_dist_lock_mgr.o

# target to build an object file
psu_dist_lock_mgr.c.o:
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_test.dir/build.make CMakeFiles/psu_dist_lock_mgr_test.dir/psu_dist_lock_mgr.c.o
.PHONY : psu_dist_lock_mgr.c.o

psu_dist_lock_mgr.i: psu_dist_lock_mgr.c.i

.PHONY : psu_dist_lock_mgr.i

# target to preprocess a source file
psu_dist_lock_mgr.c.i:
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_test.dir/build.make CMakeFiles/psu_dist_lock_mgr_test.dir/psu_dist_lock_mgr.c.i
.PHONY : psu_dist_lock_mgr.c.i

psu_dist_lock_mgr.s: psu_dist_lock_mgr.c.s

.PHONY : psu_dist_lock_mgr.s

# target to generate assembly for a file
psu_dist_lock_mgr.c.s:
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_test.dir/build.make CMakeFiles/psu_dist_lock_mgr_test.dir/psu_dist_lock_mgr.c.s
.PHONY : psu_dist_lock_mgr.c.s

psu_dist_lock_mgr_msg_clnt.o: psu_dist_lock_mgr_msg_clnt.c.o

.PHONY : psu_dist_lock_mgr_msg_clnt.o

# target to build an object file
psu_dist_lock_mgr_msg_clnt.c.o:
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_test.dir/build.make CMakeFiles/psu_dist_lock_mgr_test.dir/psu_dist_lock_mgr_msg_clnt.c.o
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_server.dir/build.make CMakeFiles/psu_dist_lock_mgr_server.dir/psu_dist_lock_mgr_msg_clnt.c.o
.PHONY : psu_dist_lock_mgr_msg_clnt.c.o

psu_dist_lock_mgr_msg_clnt.i: psu_dist_lock_mgr_msg_clnt.c.i

.PHONY : psu_dist_lock_mgr_msg_clnt.i

# target to preprocess a source file
psu_dist_lock_mgr_msg_clnt.c.i:
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_test.dir/build.make CMakeFiles/psu_dist_lock_mgr_test.dir/psu_dist_lock_mgr_msg_clnt.c.i
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_server.dir/build.make CMakeFiles/psu_dist_lock_mgr_server.dir/psu_dist_lock_mgr_msg_clnt.c.i
.PHONY : psu_dist_lock_mgr_msg_clnt.c.i

psu_dist_lock_mgr_msg_clnt.s: psu_dist_lock_mgr_msg_clnt.c.s

.PHONY : psu_dist_lock_mgr_msg_clnt.s

# target to generate assembly for a file
psu_dist_lock_mgr_msg_clnt.c.s:
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_test.dir/build.make CMakeFiles/psu_dist_lock_mgr_test.dir/psu_dist_lock_mgr_msg_clnt.c.s
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_server.dir/build.make CMakeFiles/psu_dist_lock_mgr_server.dir/psu_dist_lock_mgr_msg_clnt.c.s
.PHONY : psu_dist_lock_mgr_msg_clnt.c.s

psu_dist_lock_mgr_msg_svc.o: psu_dist_lock_mgr_msg_svc.c.o

.PHONY : psu_dist_lock_mgr_msg_svc.o

# target to build an object file
psu_dist_lock_mgr_msg_svc.c.o:
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_server.dir/build.make CMakeFiles/psu_dist_lock_mgr_server.dir/psu_dist_lock_mgr_msg_svc.c.o
.PHONY : psu_dist_lock_mgr_msg_svc.c.o

psu_dist_lock_mgr_msg_svc.i: psu_dist_lock_mgr_msg_svc.c.i

.PHONY : psu_dist_lock_mgr_msg_svc.i

# target to preprocess a source file
psu_dist_lock_mgr_msg_svc.c.i:
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_server.dir/build.make CMakeFiles/psu_dist_lock_mgr_server.dir/psu_dist_lock_mgr_msg_svc.c.i
.PHONY : psu_dist_lock_mgr_msg_svc.c.i

psu_dist_lock_mgr_msg_svc.s: psu_dist_lock_mgr_msg_svc.c.s

.PHONY : psu_dist_lock_mgr_msg_svc.s

# target to generate assembly for a file
psu_dist_lock_mgr_msg_svc.c.s:
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_server.dir/build.make CMakeFiles/psu_dist_lock_mgr_server.dir/psu_dist_lock_mgr_msg_svc.c.s
.PHONY : psu_dist_lock_mgr_msg_svc.c.s

psu_dist_lock_mgr_msg_xdr.o: psu_dist_lock_mgr_msg_xdr.c.o

.PHONY : psu_dist_lock_mgr_msg_xdr.o

# target to build an object file
psu_dist_lock_mgr_msg_xdr.c.o:
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_test.dir/build.make CMakeFiles/psu_dist_lock_mgr_test.dir/psu_dist_lock_mgr_msg_xdr.c.o
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_server.dir/build.make CMakeFiles/psu_dist_lock_mgr_server.dir/psu_dist_lock_mgr_msg_xdr.c.o
.PHONY : psu_dist_lock_mgr_msg_xdr.c.o

psu_dist_lock_mgr_msg_xdr.i: psu_dist_lock_mgr_msg_xdr.c.i

.PHONY : psu_dist_lock_mgr_msg_xdr.i

# target to preprocess a source file
psu_dist_lock_mgr_msg_xdr.c.i:
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_test.dir/build.make CMakeFiles/psu_dist_lock_mgr_test.dir/psu_dist_lock_mgr_msg_xdr.c.i
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_server.dir/build.make CMakeFiles/psu_dist_lock_mgr_server.dir/psu_dist_lock_mgr_msg_xdr.c.i
.PHONY : psu_dist_lock_mgr_msg_xdr.c.i

psu_dist_lock_mgr_msg_xdr.s: psu_dist_lock_mgr_msg_xdr.c.s

.PHONY : psu_dist_lock_mgr_msg_xdr.s

# target to generate assembly for a file
psu_dist_lock_mgr_msg_xdr.c.s:
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_test.dir/build.make CMakeFiles/psu_dist_lock_mgr_test.dir/psu_dist_lock_mgr_msg_xdr.c.s
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_server.dir/build.make CMakeFiles/psu_dist_lock_mgr_server.dir/psu_dist_lock_mgr_msg_xdr.c.s
.PHONY : psu_dist_lock_mgr_msg_xdr.c.s

psu_dist_lock_mgr_server.o: psu_dist_lock_mgr_server.c.o

.PHONY : psu_dist_lock_mgr_server.o

# target to build an object file
psu_dist_lock_mgr_server.c.o:
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_server.dir/build.make CMakeFiles/psu_dist_lock_mgr_server.dir/psu_dist_lock_mgr_server.c.o
.PHONY : psu_dist_lock_mgr_server.c.o

psu_dist_lock_mgr_server.i: psu_dist_lock_mgr_server.c.i

.PHONY : psu_dist_lock_mgr_server.i

# target to preprocess a source file
psu_dist_lock_mgr_server.c.i:
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_server.dir/build.make CMakeFiles/psu_dist_lock_mgr_server.dir/psu_dist_lock_mgr_server.c.i
.PHONY : psu_dist_lock_mgr_server.c.i

psu_dist_lock_mgr_server.s: psu_dist_lock_mgr_server.c.s

.PHONY : psu_dist_lock_mgr_server.s

# target to generate assembly for a file
psu_dist_lock_mgr_server.c.s:
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_server.dir/build.make CMakeFiles/psu_dist_lock_mgr_server.dir/psu_dist_lock_mgr_server.c.s
.PHONY : psu_dist_lock_mgr_server.c.s

psu_dist_lock_mgr_test.o: psu_dist_lock_mgr_test.c.o

.PHONY : psu_dist_lock_mgr_test.o

# target to build an object file
psu_dist_lock_mgr_test.c.o:
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_test.dir/build.make CMakeFiles/psu_dist_lock_mgr_test.dir/psu_dist_lock_mgr_test.c.o
.PHONY : psu_dist_lock_mgr_test.c.o

psu_dist_lock_mgr_test.i: psu_dist_lock_mgr_test.c.i

.PHONY : psu_dist_lock_mgr_test.i

# target to preprocess a source file
psu_dist_lock_mgr_test.c.i:
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_test.dir/build.make CMakeFiles/psu_dist_lock_mgr_test.dir/psu_dist_lock_mgr_test.c.i
.PHONY : psu_dist_lock_mgr_test.c.i

psu_dist_lock_mgr_test.s: psu_dist_lock_mgr_test.c.s

.PHONY : psu_dist_lock_mgr_test.s

# target to generate assembly for a file
psu_dist_lock_mgr_test.c.s:
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_test.dir/build.make CMakeFiles/psu_dist_lock_mgr_test.dir/psu_dist_lock_mgr_test.c.s
.PHONY : psu_dist_lock_mgr_test.c.s

psu_dsm.o: psu_dsm.c.o

.PHONY : psu_dsm.o

# target to build an object file
psu_dsm.c.o:
	$(MAKE) -f CMakeFiles/psu_dsm_test.dir/build.make CMakeFiles/psu_dsm_test.dir/psu_dsm.c.o
.PHONY : psu_dsm.c.o

psu_dsm.i: psu_dsm.c.i

.PHONY : psu_dsm.i

# target to preprocess a source file
psu_dsm.c.i:
	$(MAKE) -f CMakeFiles/psu_dsm_test.dir/build.make CMakeFiles/psu_dsm_test.dir/psu_dsm.c.i
.PHONY : psu_dsm.c.i

psu_dsm.s: psu_dsm.c.s

.PHONY : psu_dsm.s

# target to generate assembly for a file
psu_dsm.c.s:
	$(MAKE) -f CMakeFiles/psu_dsm_test.dir/build.make CMakeFiles/psu_dsm_test.dir/psu_dsm.c.s
.PHONY : psu_dsm.c.s

psu_dsm_msg_clnt.o: psu_dsm_msg_clnt.c.o

.PHONY : psu_dsm_msg_clnt.o

# target to build an object file
psu_dsm_msg_clnt.c.o:
	$(MAKE) -f CMakeFiles/psu_dsm_server.dir/build.make CMakeFiles/psu_dsm_server.dir/psu_dsm_msg_clnt.c.o
	$(MAKE) -f CMakeFiles/psu_dsm_test.dir/build.make CMakeFiles/psu_dsm_test.dir/psu_dsm_msg_clnt.c.o
.PHONY : psu_dsm_msg_clnt.c.o

psu_dsm_msg_clnt.i: psu_dsm_msg_clnt.c.i

.PHONY : psu_dsm_msg_clnt.i

# target to preprocess a source file
psu_dsm_msg_clnt.c.i:
	$(MAKE) -f CMakeFiles/psu_dsm_server.dir/build.make CMakeFiles/psu_dsm_server.dir/psu_dsm_msg_clnt.c.i
	$(MAKE) -f CMakeFiles/psu_dsm_test.dir/build.make CMakeFiles/psu_dsm_test.dir/psu_dsm_msg_clnt.c.i
.PHONY : psu_dsm_msg_clnt.c.i

psu_dsm_msg_clnt.s: psu_dsm_msg_clnt.c.s

.PHONY : psu_dsm_msg_clnt.s

# target to generate assembly for a file
psu_dsm_msg_clnt.c.s:
	$(MAKE) -f CMakeFiles/psu_dsm_server.dir/build.make CMakeFiles/psu_dsm_server.dir/psu_dsm_msg_clnt.c.s
	$(MAKE) -f CMakeFiles/psu_dsm_test.dir/build.make CMakeFiles/psu_dsm_test.dir/psu_dsm_msg_clnt.c.s
.PHONY : psu_dsm_msg_clnt.c.s

psu_dsm_msg_svc.o: psu_dsm_msg_svc.c.o

.PHONY : psu_dsm_msg_svc.o

# target to build an object file
psu_dsm_msg_svc.c.o:
	$(MAKE) -f CMakeFiles/psu_dsm_server.dir/build.make CMakeFiles/psu_dsm_server.dir/psu_dsm_msg_svc.c.o
.PHONY : psu_dsm_msg_svc.c.o

psu_dsm_msg_svc.i: psu_dsm_msg_svc.c.i

.PHONY : psu_dsm_msg_svc.i

# target to preprocess a source file
psu_dsm_msg_svc.c.i:
	$(MAKE) -f CMakeFiles/psu_dsm_server.dir/build.make CMakeFiles/psu_dsm_server.dir/psu_dsm_msg_svc.c.i
.PHONY : psu_dsm_msg_svc.c.i

psu_dsm_msg_svc.s: psu_dsm_msg_svc.c.s

.PHONY : psu_dsm_msg_svc.s

# target to generate assembly for a file
psu_dsm_msg_svc.c.s:
	$(MAKE) -f CMakeFiles/psu_dsm_server.dir/build.make CMakeFiles/psu_dsm_server.dir/psu_dsm_msg_svc.c.s
.PHONY : psu_dsm_msg_svc.c.s

psu_dsm_msg_xdr.o: psu_dsm_msg_xdr.c.o

.PHONY : psu_dsm_msg_xdr.o

# target to build an object file
psu_dsm_msg_xdr.c.o:
	$(MAKE) -f CMakeFiles/psu_dsm_server.dir/build.make CMakeFiles/psu_dsm_server.dir/psu_dsm_msg_xdr.c.o
	$(MAKE) -f CMakeFiles/psu_dsm_test.dir/build.make CMakeFiles/psu_dsm_test.dir/psu_dsm_msg_xdr.c.o
.PHONY : psu_dsm_msg_xdr.c.o

psu_dsm_msg_xdr.i: psu_dsm_msg_xdr.c.i

.PHONY : psu_dsm_msg_xdr.i

# target to preprocess a source file
psu_dsm_msg_xdr.c.i:
	$(MAKE) -f CMakeFiles/psu_dsm_server.dir/build.make CMakeFiles/psu_dsm_server.dir/psu_dsm_msg_xdr.c.i
	$(MAKE) -f CMakeFiles/psu_dsm_test.dir/build.make CMakeFiles/psu_dsm_test.dir/psu_dsm_msg_xdr.c.i
.PHONY : psu_dsm_msg_xdr.c.i

psu_dsm_msg_xdr.s: psu_dsm_msg_xdr.c.s

.PHONY : psu_dsm_msg_xdr.s

# target to generate assembly for a file
psu_dsm_msg_xdr.c.s:
	$(MAKE) -f CMakeFiles/psu_dsm_server.dir/build.make CMakeFiles/psu_dsm_server.dir/psu_dsm_msg_xdr.c.s
	$(MAKE) -f CMakeFiles/psu_dsm_test.dir/build.make CMakeFiles/psu_dsm_test.dir/psu_dsm_msg_xdr.c.s
.PHONY : psu_dsm_msg_xdr.c.s

psu_dsm_server.o: psu_dsm_server.c.o

.PHONY : psu_dsm_server.o

# target to build an object file
psu_dsm_server.c.o:
	$(MAKE) -f CMakeFiles/psu_dsm_server.dir/build.make CMakeFiles/psu_dsm_server.dir/psu_dsm_server.c.o
	$(MAKE) -f CMakeFiles/psu_dsm_test.dir/build.make CMakeFiles/psu_dsm_test.dir/psu_dsm_server.c.o
.PHONY : psu_dsm_server.c.o

psu_dsm_server.i: psu_dsm_server.c.i

.PHONY : psu_dsm_server.i

# target to preprocess a source file
psu_dsm_server.c.i:
	$(MAKE) -f CMakeFiles/psu_dsm_server.dir/build.make CMakeFiles/psu_dsm_server.dir/psu_dsm_server.c.i
	$(MAKE) -f CMakeFiles/psu_dsm_test.dir/build.make CMakeFiles/psu_dsm_test.dir/psu_dsm_server.c.i
.PHONY : psu_dsm_server.c.i

psu_dsm_server.s: psu_dsm_server.c.s

.PHONY : psu_dsm_server.s

# target to generate assembly for a file
psu_dsm_server.c.s:
	$(MAKE) -f CMakeFiles/psu_dsm_server.dir/build.make CMakeFiles/psu_dsm_server.dir/psu_dsm_server.c.s
	$(MAKE) -f CMakeFiles/psu_dsm_test.dir/build.make CMakeFiles/psu_dsm_test.dir/psu_dsm_server.c.s
.PHONY : psu_dsm_server.c.s

psu_dsm_test.o: psu_dsm_test.c.o

.PHONY : psu_dsm_test.o

# target to build an object file
psu_dsm_test.c.o:
	$(MAKE) -f CMakeFiles/psu_dsm_test.dir/build.make CMakeFiles/psu_dsm_test.dir/psu_dsm_test.c.o
.PHONY : psu_dsm_test.c.o

psu_dsm_test.i: psu_dsm_test.c.i

.PHONY : psu_dsm_test.i

# target to preprocess a source file
psu_dsm_test.c.i:
	$(MAKE) -f CMakeFiles/psu_dsm_test.dir/build.make CMakeFiles/psu_dsm_test.dir/psu_dsm_test.c.i
.PHONY : psu_dsm_test.c.i

psu_dsm_test.s: psu_dsm_test.c.s

.PHONY : psu_dsm_test.s

# target to generate assembly for a file
psu_dsm_test.c.s:
	$(MAKE) -f CMakeFiles/psu_dsm_test.dir/build.make CMakeFiles/psu_dsm_test.dir/psu_dsm_test.c.s
.PHONY : psu_dsm_test.c.s

psu_thread.o: psu_thread.c.o

.PHONY : psu_thread.o

# target to build an object file
psu_thread.c.o:
	$(MAKE) -f CMakeFiles/psu_thread_test.dir/build.make CMakeFiles/psu_thread_test.dir/psu_thread.c.o
.PHONY : psu_thread.c.o

psu_thread.i: psu_thread.c.i

.PHONY : psu_thread.i

# target to preprocess a source file
psu_thread.c.i:
	$(MAKE) -f CMakeFiles/psu_thread_test.dir/build.make CMakeFiles/psu_thread_test.dir/psu_thread.c.i
.PHONY : psu_thread.c.i

psu_thread.s: psu_thread.c.s

.PHONY : psu_thread.s

# target to generate assembly for a file
psu_thread.c.s:
	$(MAKE) -f CMakeFiles/psu_thread_test.dir/build.make CMakeFiles/psu_thread_test.dir/psu_thread.c.s
.PHONY : psu_thread.c.s

psu_thread_msg_clnt.o: psu_thread_msg_clnt.c.o

.PHONY : psu_thread_msg_clnt.o

# target to build an object file
psu_thread_msg_clnt.c.o:
	$(MAKE) -f CMakeFiles/psu_thread_test.dir/build.make CMakeFiles/psu_thread_test.dir/psu_thread_msg_clnt.c.o
.PHONY : psu_thread_msg_clnt.c.o

psu_thread_msg_clnt.i: psu_thread_msg_clnt.c.i

.PHONY : psu_thread_msg_clnt.i

# target to preprocess a source file
psu_thread_msg_clnt.c.i:
	$(MAKE) -f CMakeFiles/psu_thread_test.dir/build.make CMakeFiles/psu_thread_test.dir/psu_thread_msg_clnt.c.i
.PHONY : psu_thread_msg_clnt.c.i

psu_thread_msg_clnt.s: psu_thread_msg_clnt.c.s

.PHONY : psu_thread_msg_clnt.s

# target to generate assembly for a file
psu_thread_msg_clnt.c.s:
	$(MAKE) -f CMakeFiles/psu_thread_test.dir/build.make CMakeFiles/psu_thread_test.dir/psu_thread_msg_clnt.c.s
.PHONY : psu_thread_msg_clnt.c.s

psu_thread_msg_svc.o: psu_thread_msg_svc.c.o

.PHONY : psu_thread_msg_svc.o

# target to build an object file
psu_thread_msg_svc.c.o:
	$(MAKE) -f CMakeFiles/psu_thread_test.dir/build.make CMakeFiles/psu_thread_test.dir/psu_thread_msg_svc.c.o
.PHONY : psu_thread_msg_svc.c.o

psu_thread_msg_svc.i: psu_thread_msg_svc.c.i

.PHONY : psu_thread_msg_svc.i

# target to preprocess a source file
psu_thread_msg_svc.c.i:
	$(MAKE) -f CMakeFiles/psu_thread_test.dir/build.make CMakeFiles/psu_thread_test.dir/psu_thread_msg_svc.c.i
.PHONY : psu_thread_msg_svc.c.i

psu_thread_msg_svc.s: psu_thread_msg_svc.c.s

.PHONY : psu_thread_msg_svc.s

# target to generate assembly for a file
psu_thread_msg_svc.c.s:
	$(MAKE) -f CMakeFiles/psu_thread_test.dir/build.make CMakeFiles/psu_thread_test.dir/psu_thread_msg_svc.c.s
.PHONY : psu_thread_msg_svc.c.s

psu_thread_msg_xdr.o: psu_thread_msg_xdr.c.o

.PHONY : psu_thread_msg_xdr.o

# target to build an object file
psu_thread_msg_xdr.c.o:
	$(MAKE) -f CMakeFiles/psu_thread_test.dir/build.make CMakeFiles/psu_thread_test.dir/psu_thread_msg_xdr.c.o
.PHONY : psu_thread_msg_xdr.c.o

psu_thread_msg_xdr.i: psu_thread_msg_xdr.c.i

.PHONY : psu_thread_msg_xdr.i

# target to preprocess a source file
psu_thread_msg_xdr.c.i:
	$(MAKE) -f CMakeFiles/psu_thread_test.dir/build.make CMakeFiles/psu_thread_test.dir/psu_thread_msg_xdr.c.i
.PHONY : psu_thread_msg_xdr.c.i

psu_thread_msg_xdr.s: psu_thread_msg_xdr.c.s

.PHONY : psu_thread_msg_xdr.s

# target to generate assembly for a file
psu_thread_msg_xdr.c.s:
	$(MAKE) -f CMakeFiles/psu_thread_test.dir/build.make CMakeFiles/psu_thread_test.dir/psu_thread_msg_xdr.c.s
.PHONY : psu_thread_msg_xdr.c.s

psu_thread_server.o: psu_thread_server.c.o

.PHONY : psu_thread_server.o

# target to build an object file
psu_thread_server.c.o:
	$(MAKE) -f CMakeFiles/psu_thread_test.dir/build.make CMakeFiles/psu_thread_test.dir/psu_thread_server.c.o
.PHONY : psu_thread_server.c.o

psu_thread_server.i: psu_thread_server.c.i

.PHONY : psu_thread_server.i

# target to preprocess a source file
psu_thread_server.c.i:
	$(MAKE) -f CMakeFiles/psu_thread_test.dir/build.make CMakeFiles/psu_thread_test.dir/psu_thread_server.c.i
.PHONY : psu_thread_server.c.i

psu_thread_server.s: psu_thread_server.c.s

.PHONY : psu_thread_server.s

# target to generate assembly for a file
psu_thread_server.c.s:
	$(MAKE) -f CMakeFiles/psu_thread_test.dir/build.make CMakeFiles/psu_thread_test.dir/psu_thread_server.c.s
.PHONY : psu_thread_server.c.s

psu_thread_test.o: psu_thread_test.c.o

.PHONY : psu_thread_test.o

# target to build an object file
psu_thread_test.c.o:
	$(MAKE) -f CMakeFiles/psu_thread_test.dir/build.make CMakeFiles/psu_thread_test.dir/psu_thread_test.c.o
.PHONY : psu_thread_test.c.o

psu_thread_test.i: psu_thread_test.c.i

.PHONY : psu_thread_test.i

# target to preprocess a source file
psu_thread_test.c.i:
	$(MAKE) -f CMakeFiles/psu_thread_test.dir/build.make CMakeFiles/psu_thread_test.dir/psu_thread_test.c.i
.PHONY : psu_thread_test.c.i

psu_thread_test.s: psu_thread_test.c.s

.PHONY : psu_thread_test.s

# target to generate assembly for a file
psu_thread_test.c.s:
	$(MAKE) -f CMakeFiles/psu_thread_test.dir/build.make CMakeFiles/psu_thread_test.dir/psu_thread_test.c.s
.PHONY : psu_thread_test.c.s

util.o: util.c.o

.PHONY : util.o

# target to build an object file
util.c.o:
	$(MAKE) -f CMakeFiles/psu_dsm_server.dir/build.make CMakeFiles/psu_dsm_server.dir/util.c.o
	$(MAKE) -f CMakeFiles/psu_dsm_test.dir/build.make CMakeFiles/psu_dsm_test.dir/util.c.o
.PHONY : util.c.o

util.i: util.c.i

.PHONY : util.i

# target to preprocess a source file
util.c.i:
	$(MAKE) -f CMakeFiles/psu_dsm_server.dir/build.make CMakeFiles/psu_dsm_server.dir/util.c.i
	$(MAKE) -f CMakeFiles/psu_dsm_test.dir/build.make CMakeFiles/psu_dsm_test.dir/util.c.i
.PHONY : util.c.i

util.s: util.c.s

.PHONY : util.s

# target to generate assembly for a file
util.c.s:
	$(MAKE) -f CMakeFiles/psu_dsm_server.dir/build.make CMakeFiles/psu_dsm_server.dir/util.c.s
	$(MAKE) -f CMakeFiles/psu_dsm_test.dir/build.make CMakeFiles/psu_dsm_test.dir/util.c.s
.PHONY : util.c.s

utility.o: utility.c.o

.PHONY : utility.o

# target to build an object file
utility.c.o:
	$(MAKE) -f CMakeFiles/psu_thread_test.dir/build.make CMakeFiles/psu_thread_test.dir/utility.c.o
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_test.dir/build.make CMakeFiles/psu_dist_lock_mgr_test.dir/utility.c.o
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_server.dir/build.make CMakeFiles/psu_dist_lock_mgr_server.dir/utility.c.o
.PHONY : utility.c.o

utility.i: utility.c.i

.PHONY : utility.i

# target to preprocess a source file
utility.c.i:
	$(MAKE) -f CMakeFiles/psu_thread_test.dir/build.make CMakeFiles/psu_thread_test.dir/utility.c.i
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_test.dir/build.make CMakeFiles/psu_dist_lock_mgr_test.dir/utility.c.i
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_server.dir/build.make CMakeFiles/psu_dist_lock_mgr_server.dir/utility.c.i
.PHONY : utility.c.i

utility.s: utility.c.s

.PHONY : utility.s

# target to generate assembly for a file
utility.c.s:
	$(MAKE) -f CMakeFiles/psu_thread_test.dir/build.make CMakeFiles/psu_thread_test.dir/utility.c.s
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_test.dir/build.make CMakeFiles/psu_dist_lock_mgr_test.dir/utility.c.s
	$(MAKE) -f CMakeFiles/psu_dist_lock_mgr_server.dir/build.make CMakeFiles/psu_dist_lock_mgr_server.dir/utility.c.s
.PHONY : utility.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... psu_thread_test"
	@echo "... psu_dsm_server"
	@echo "... psu_dist_lock_mgr_test"
	@echo "... psu_dsm_test"
	@echo "... edit_cache"
	@echo "... psu_dist_lock_mgr_server"
	@echo "... psu_dist_lock_mgr.o"
	@echo "... psu_dist_lock_mgr.i"
	@echo "... psu_dist_lock_mgr.s"
	@echo "... psu_dist_lock_mgr_msg_clnt.o"
	@echo "... psu_dist_lock_mgr_msg_clnt.i"
	@echo "... psu_dist_lock_mgr_msg_clnt.s"
	@echo "... psu_dist_lock_mgr_msg_svc.o"
	@echo "... psu_dist_lock_mgr_msg_svc.i"
	@echo "... psu_dist_lock_mgr_msg_svc.s"
	@echo "... psu_dist_lock_mgr_msg_xdr.o"
	@echo "... psu_dist_lock_mgr_msg_xdr.i"
	@echo "... psu_dist_lock_mgr_msg_xdr.s"
	@echo "... psu_dist_lock_mgr_server.o"
	@echo "... psu_dist_lock_mgr_server.i"
	@echo "... psu_dist_lock_mgr_server.s"
	@echo "... psu_dist_lock_mgr_test.o"
	@echo "... psu_dist_lock_mgr_test.i"
	@echo "... psu_dist_lock_mgr_test.s"
	@echo "... psu_dsm.o"
	@echo "... psu_dsm.i"
	@echo "... psu_dsm.s"
	@echo "... psu_dsm_msg_clnt.o"
	@echo "... psu_dsm_msg_clnt.i"
	@echo "... psu_dsm_msg_clnt.s"
	@echo "... psu_dsm_msg_svc.o"
	@echo "... psu_dsm_msg_svc.i"
	@echo "... psu_dsm_msg_svc.s"
	@echo "... psu_dsm_msg_xdr.o"
	@echo "... psu_dsm_msg_xdr.i"
	@echo "... psu_dsm_msg_xdr.s"
	@echo "... psu_dsm_server.o"
	@echo "... psu_dsm_server.i"
	@echo "... psu_dsm_server.s"
	@echo "... psu_dsm_test.o"
	@echo "... psu_dsm_test.i"
	@echo "... psu_dsm_test.s"
	@echo "... psu_thread.o"
	@echo "... psu_thread.i"
	@echo "... psu_thread.s"
	@echo "... psu_thread_msg_clnt.o"
	@echo "... psu_thread_msg_clnt.i"
	@echo "... psu_thread_msg_clnt.s"
	@echo "... psu_thread_msg_svc.o"
	@echo "... psu_thread_msg_svc.i"
	@echo "... psu_thread_msg_svc.s"
	@echo "... psu_thread_msg_xdr.o"
	@echo "... psu_thread_msg_xdr.i"
	@echo "... psu_thread_msg_xdr.s"
	@echo "... psu_thread_server.o"
	@echo "... psu_thread_server.i"
	@echo "... psu_thread_server.s"
	@echo "... psu_thread_test.o"
	@echo "... psu_thread_test.i"
	@echo "... psu_thread_test.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
	@echo "... utility.o"
	@echo "... utility.i"
	@echo "... utility.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

