/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "psu_dsm_msg.h"
#include "psu_dsm_msg_svc.h"
#include "util.h"

unsigned int nserver;
serverid_t server[MAX_SERV];
dir_t *dir;
dsm_t *dsm;

int *
psu_dsm_page_find_1_svc(pageid_t *argp, struct svc_req *rqstp)
{
	static int  result;
	if(search_dir(*argp, dir) == NULL)
		result = 0;
	else
		result = 1;
	printf("rpc called: page_find(); return = %d\n", result);
	return &result;
}

host_t *
psu_dsm_page_locate_1_svc(pageid_t *argp, struct svc_req *rqstp)
{
	static host_t  result;
	

	int i;
	pageid_t pageid;
	char local_host[IP_LEN];
	get_local_ipaddr(local_host);
	
	printf("server %s called: page_creat\n", local_host);
	
	pageid = *argp;
		
	//search local dir
	if(search_dir(pageid, dir) == NULL){
		strncpy(result.ip, local_host, IP_LEN);
		return &result;
	}
	
	// search remote dir
	for(i = 0; i < nserver; i++){
		if(strncmp(server[i], local_host, IP_LEN) != 0){
			CLIENT *clnt;
			int *result_1;
	
			clnt = clnt_create (server[i], PSU_DSM, PSU_DSM_VERS, "tcp");
			if (clnt == NULL) {
				clnt_pcreateerror (server[i]);
				exit (1);
			}

			result_1 = psu_dsm_page_find_1(argp, clnt);
			if (result_1 == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}

			clnt_destroy (clnt);
			if(*result_1 == 1){
				strncpy(result.ip, server[i], IP_LEN);
    				return &result;
			}
		}
	}

	// page doesn't exist, create on local server.
	strncpy(result.ip, "", IP_LEN);
	return &result;
}


int *
psu_dsm_page_creat_1_svc(pageid_t *argp, struct svc_req *rqstp)
{

	static int  result;


	int i;
	pageid_t pageid;
	char local_host[IP_LEN];
	get_local_ipaddr(local_host);
	
	printf("server %s called: page_creat\n", local_host);
	
	pageid = *argp;
		
	//search local dir
	if(search_dir(pageid, dir) != NULL){

		request_t req;
		req.pageid = pageid;
		req.mode = RW;

		CLIENT *clnt;
		page_t *result_1;
		clnt = clnt_create (local_host, PSU_DSM, PSU_DSM_VERS, "tcp");
		if (clnt == NULL) {
			clnt_pcreateerror (local_host);
			exit (1);
		}

		result_1 = psu_dsm_page_request_1(&req, clnt);
		if (result_1 == (page_t *) NULL) {
			clnt_perror (clnt, "call failed");
		}

		clnt_destroy (clnt);

		key_t key;
		int shmid;

		key = hash(pageid.name);
		shmid = shmget(key, PAGE_SIZE, 0644 | IPC_CREAT);

		if(shmid == -1){
			perror("shmget\n");
			exit(1);
		}

		void *addr;
		addr = shmat(shmid, (void *)0, 0);
		mprotect(addr, PAGE_SIZE, PROT_WRITE);
		memcpy(addr, result_1, PAGE_SIZE);
		
		insert_dsm(pageid, local_host, dsm);
		result = 1;
		return &result;
	}

	
	// search remote dir
	for(i = 0; i < nserver; i++){
		if(strncmp(server[i], local_host, IP_LEN) != 0){
			CLIENT *clnt;
			int *result_1;
	
			clnt = clnt_create (server[i], PSU_DSM, PSU_DSM_VERS, "tcp");
			if (clnt == NULL) {
				clnt_pcreateerror (server[i]);
				exit (1);
			}

			result_1 = psu_dsm_page_find_1(argp, clnt);
			if (result_1 == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}

			clnt_destroy (clnt);
			if(*result_1 == 1){


				request_t req;
				req.pageid = pageid;
				req.mode = NA;

				CLIENT *clnt;
				page_t *result_2;
				clnt = clnt_create (server[i], PSU_DSM, PSU_DSM_VERS, "tcp");
				if (clnt == NULL) {
					clnt_pcreateerror (server[i]);
					exit (1);
				}

				result_2 = psu_dsm_page_request_1(&req, clnt);
				if (result_2 == (page_t *) NULL) {
					clnt_perror (clnt, "call failed");
				}

				clnt_destroy (clnt);

				key_t key;
				int shmid;

				key = hash(pageid.name);
				shmid = shmget(key, PAGE_SIZE, 0644 | IPC_CREAT);

				if(shmid == -1){
					perror("shmget\n");
					exit(1);
				}

				void *addr;
				addr = shmat(shmid, (void *)0, 0);
				mprotect(addr, PAGE_SIZE, PROT_WRITE);
				memcpy(addr, result_1, PAGE_SIZE);
		
				insert_dsm(pageid, server[i], dsm);
				result = 1;
				return &result;

			}
		}
	}



	// page doesn't exist, create on local server.
	dir_entry_t new_entry;
	new_entry.page = pageid;
	int idx = get_server_id(local_host);
	int j;
	for(j = 0; j < MAX_SERV; j++){
		new_entry.pbits[j] = NA;
	}
	new_entry.pbits[idx] = RW;
	new_entry.mode = RW;

	insert_dir(new_entry, dir);
	
 	key_t key;
	int shmid;

	key = hash(pageid.name);
	shmid = shmget(key, PAGE_SIZE, 0666 | IPC_CREAT);

	if(shmid == -1){
		perror("shmget\n");
		exit(1);
	}

	void *addr;
	addr = shmat(shmid, (void *)0, 0);
	insert_dsm(pageid, local_host, dsm);

	mprotect(addr, PAGE_SIZE, PROT_WRITE);
	result = 1;
	return &result;

}

int *
psu_dsm_page_update_1_svc(request_t *argp, struct svc_req *rqstp)
{
	static int  result;
	pageid_t pageid = argp->pageid;
	mode_t mode = argp->mode;
	dsm_t *dp =search_dsm(pageid, dsm);
	if(dp == NULL){
		perror("no such dsm");
		exit(1);
	} 
	void* addr = dp->entry.addr;

	if(mode == RO){
		mprotect(addr, PAGE_SIZE, PROT_READ);
	}
	if(mode == RW){
		mprotect(addr, PAGE_SIZE, PROT_NONE);
	}


	
	/*
	 * insert server code here
	 */

	return &result;
}

page_t *
psu_dsm_page_request_1_svc(request_t *argp, struct svc_req *rqstp)
{
	static page_t  result;

	pageid_t pageid;
	mode_t mode;

	pageid = argp->pageid;
	dir_t *dirp = search_dir(pageid, dir);
	if(dirp==NULL){
		perror("no such dir entry");
		exit(1);
	}
	
	int i;

	if(mode == RO){
		for(i = 0; i < MAX_SERV; i++){
			if(dirp->entry.pbits[i] == 1){
				CLIENT *clnt;
				page_t *result_1;
				
				clnt = clnt_create (server[i], PSU_DSM, PSU_DSM_VERS, "tcp");
				if (clnt == NULL) {
					clnt_pcreateerror (server[i]);
					exit (1);
				}

				result_1 = psu_dsm_page_fetch_1(argp, clnt);
				if (result_1 == (page_t *) NULL) {
					clnt_perror (clnt, "call failed");
				}


				if(dirp->entry.mode == RW){
					int *result_2;
					result_2 = psu_dsm_page_update_1(argp, clnt);
					if (result_2 == (int *) NULL) {
						clnt_perror (clnt, "call failed");
					}
				}

				clnt_destroy (clnt);
				
				result = *result_1;
				break;
			}
		
		}
		int iserv = get_server_id(argp->from);

		dirp->entry.pbits[iserv] = RO;
		
	}

	if(mode == RW){
		int first = 0;
		for(i = 0; i < MAX_SERV; i++){
			if(dirp->entry.pbits[i] == 1){
				first++;
				CLIENT *clnt;
				page_t *result_1;
				int *result_2;
	
				clnt = clnt_create (server[i], PSU_DSM, PSU_DSM_VERS, "tcp");
				
				if (clnt == NULL) {
					clnt_pcreateerror (server[i]);
					exit (1);
				}

				if(first == 1){
					result_1 = psu_dsm_page_fetch_1(argp, clnt);
					if (result_1 == (page_t *) NULL) {
						clnt_perror (clnt, "call failed");
					}
					result = *result_1;
				}

				result_2 = psu_dsm_page_update_1(argp, clnt);
				if (result_2 == (int *) NULL) {
					clnt_perror (clnt, "call failed");
				}

				clnt_destroy (clnt);				
					
			}
		
		}
		int iserv = get_server_id(argp->from);

		dirp->entry.pbits[iserv] = RW;
		//todo: change pbits here
	}



/*
	 * insert server code here
	 */

	return &result;
}

page_t *
psu_dsm_page_fetch_1_svc(request_t *argp, struct svc_req *rqstp)
{
	static page_t  result;
	pageid_t pageid;

	pageid = argp->pageid;
	dsm_t *p = search_dsm(pageid, dsm);
	if(p==NULL){
		perror("no such memory");
		exit(1);
	}
	
	
	memcpy(result.addr, p->entry.addr, PAGE_SIZE);
	result.size = pageid.size;

	return &result;
}

void *
psu_dsm_page_ack_1_svc(pageid_t *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}
